/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Mauricio
 */
public class DeTodoSA extends javax.swing.JFrame {

    /**
     * Creates new form DeTodoSA
     */
    public DeTodoSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenu = new javax.swing.JMenu();
        mbarAdm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mbarRubro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mbarNombre = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mbarPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jmenu.setText("Administracion");
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });

        mbarAdm.setText("Administracion Productos");
        mbarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbarAdmActionPerformed(evt);
            }
        });
        jmenu.add(mbarAdm);

        jMenuBar1.add(jmenu);

        jMenu2.setText("Consultas");

        mbarRubro.setText("Lista Rubro");
        mbarRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbarRubroActionPerformed(evt);
            }
        });
        jMenu2.add(mbarRubro);
        jMenu2.add(jSeparator1);

        mbarNombre.setText("Lista Nombre");
        mbarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbarNombreActionPerformed(evt);
            }
        });
        jMenu2.add(mbarNombre);
        jMenu2.add(jSeparator2);

        mbarPrecio.setText("Lista Precio");
        mbarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbarPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(mbarPrecio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarRubroActionPerformed
        ListadoRubro lista=new ListadoRubro();
        jDesktopPane1.add(lista);
        lista.setVisible(true);
    }//GEN-LAST:event_mbarRubroActionPerformed

    private void mbarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarPrecioActionPerformed
        Listado_Precio lis=new Listado_Precio();
        jDesktopPane1.add(lis);
        lis.setVisible(true);
    }//GEN-LAST:event_mbarPrecioActionPerformed

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        
    }//GEN-LAST:event_jmenuActionPerformed

    private void mbarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarAdmActionPerformed
        Getion_Productos internal=new Getion_Productos();
        jDesktopPane1.add(internal);
        internal.setVisible(true);
    }//GEN-LAST:event_mbarAdmActionPerformed

    private void mbarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarNombreActionPerformed
       Listado_Nombre lista=new Listado_Nombre();
        jDesktopPane1.add(lista);
        lista.setVisible(true);
    }//GEN-LAST:event_mbarNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodoSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu jmenu;
    private javax.swing.JMenuItem mbarAdm;
    private javax.swing.JMenuItem mbarNombre;
    private javax.swing.JMenuItem mbarPrecio;
    private javax.swing.JMenuItem mbarRubro;
    // End of variables declaration//GEN-END:variables
}
