/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.DepositoProductos;
import entity.Producto;
import java.util.TreeSet;
import javax.swing.JInternalFrame;

/**
 *
 * @author Mauricio
 */
public class DeTodoSA extends javax.swing.JFrame {

    /**
     * Creates new form DeTodoSA
     */
    
    private TreeSet<Producto> productos = new TreeSet<>();
    
    public DeTodoSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        mnbMenu = new javax.swing.JMenuBar();
        mniProductos = new javax.swing.JMenu();
        mbarAdm = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mniRubro = new javax.swing.JMenuItem();
        psrSeparador1 = new javax.swing.JPopupMenu.Separator();
        mniNombre = new javax.swing.JMenuItem();
        psrSeparador2 = new javax.swing.JPopupMenu.Separator();
        mniPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        mniProductos.setText("Administracion");
        mniProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProductosActionPerformed(evt);
            }
        });

        mbarAdm.setText("Administracion Productos");
        mbarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbarAdmActionPerformed(evt);
            }
        });
        mniProductos.add(mbarAdm);

        mnbMenu.add(mniProductos);

        mnuConsultas.setText("Consultas");

        mniRubro.setText("Lista Rubro");
        mniRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRubroActionPerformed(evt);
            }
        });
        mnuConsultas.add(mniRubro);
        mnuConsultas.add(psrSeparador1);

        mniNombre.setText("Lista Nombre");
        mniNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNombreActionPerformed(evt);
            }
        });
        mnuConsultas.add(mniNombre);
        mnuConsultas.add(psrSeparador2);

        mniPrecio.setText("Lista Precio");
        mniPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPrecioActionPerformed(evt);
            }
        });
        mnuConsultas.add(mniPrecio);

        mnbMenu.add(mnuConsultas);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRubroActionPerformed
        ListadoRubro listaRubro=new ListadoRubro();
        abrirYCentrar(listaRubro);
    }//GEN-LAST:event_mniRubroActionPerformed

    private void mniPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPrecioActionPerformed
        Listado_Precio listaPrecio=new Listado_Precio();
        abrirYCentrar(listaPrecio);
    }//GEN-LAST:event_mniPrecioActionPerformed

    private void mniProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProductosActionPerformed
        
    }//GEN-LAST:event_mniProductosActionPerformed

    private void mbarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarAdmActionPerformed
        Getion_Productos internal=new Getion_Productos();
        abrirYCentrar(internal);
    }//GEN-LAST:event_mbarAdmActionPerformed

    private void mniNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNombreActionPerformed
       Listado_Nombre listaNombre = new Listado_Nombre();
        abrirYCentrar(listaNombre);
    }//GEN-LAST:event_mniNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void abrirYCentrar(JInternalFrame frame) {
        escritorio.add(frame);
        frame.pack(); 
        frame.setVisible(true);

        int x = (escritorio.getWidth() - frame.getWidth()) / 2;
        int y = (escritorio.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(x, y);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodoSA().setVisible(true);
            }
        });
        
        Producto p1 = new Producto(8172,"Perfume", 1200.00, 25, "PERFUMERIA");
        Producto p2 = new Producto(7123,"Desodorante", 1800.50, 10, "PERFUMERIA");
        Producto p3 = new Producto(9273,"Banana", 200.00, 59, "COMESTIBLE");
        Producto p4 = new Producto(1825,"Cereal", 2230.00, 15, "COMESTIBLE");
        Producto p5 = new Producto(3372,"Lavandina", 1700.00, 30, "LIMPIEZA");
        Producto p6 = new Producto(3372,"Detergente", 1800.00, 23, "LIMPIEZA");
        
        DepositoProductos.altaProducto(p1);
        DepositoProductos.altaProducto(p2);
        DepositoProductos.altaProducto(p3);
        DepositoProductos.altaProducto(p4);
        DepositoProductos.altaProducto(p5);
        DepositoProductos.altaProducto(p6);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem mbarAdm;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniNombre;
    private javax.swing.JMenuItem mniPrecio;
    private javax.swing.JMenu mniProductos;
    private javax.swing.JMenuItem mniRubro;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JPopupMenu.Separator psrSeparador1;
    private javax.swing.JPopupMenu.Separator psrSeparador2;
    // End of variables declaration//GEN-END:variables
}
